sudo: required
services:
    - docker

before_install:
    - docker build -t satsingh/docker-react -f Dockerfile.dev .

# series of commands to be ran if we wanna run tests
script:
    - docker run -e CI=True satsingh/docker-react npm run test -- --coverage