FROM node:alpine

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
RUN npm config set registry http://registry.npmjs.org/

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]